### ISSUE TITLE
Suport for ALVR v19.0.0+

### ISSUE THREAD

**Issue by tajo48** [korejan/ALXR-nightly#4]
ALXR is incompatible with recent ALVR releases due to protocol modifications.
Updating it could enhance its compatibility and usability, benefiting the user community by resolving bugs and limitations in older versions of ALVR.

**Comment by korejan** [comment]
@tajo48 Hello, this isn't really the place to post issues, please post them [here](https://github.com/korejan/ALVR/issues) in the future. There is already an issue ticket for this so need to make a new one. v19/20 support will come. Afer this post i will be disable post on this repository as it is only for CI builds.
